Repository codeit-bootcamp-spring/5-sprint-mission, pull requests merged in 2025-08, with the labels that each got.

#82 [서찬규] sprint2
  CHANNEL/13e87346-684d-4e5b-9140-d924f29ff020.ser
  CHANNEL/2e795119-a7e2-4a18-abd3-19b1b09eaa1f.ser
  CHANNEL/6be8a320-82e9-4e88-9a98-25e8c25d16e8.ser
  CHANNEL/954311d9-7664-453b-b689-ca11b1ff6598.ser
  CHANNEL/be8b3470-d26d-433c-9dd2-982e907f313b.ser
  MESSAGE/0387931c-99bb-442b-baa5-24d7fdc9f1c4.ser
  MESSAGE/44a92d6a-4c3e-422b-8f45-9b11ea18c47d.ser
  MESSAGE/4a3a169f-2391-45d2-b989-a6fbaea38bb2.ser
  MESSAGE/5814a058-9113-49d7-a54e-85f88e91547e.ser
  MESSAGE/8f2ce37c-c3ba-4c4d-9f5a-7713559442bb.ser
  MESSAGE/c7d569bb-1928-459e-b019-494d998154c5.ser
  USER/1698c404-aa1b-4ecf-a240-2572fea14445.ser
  USER/3533e20d-20c4-44a2-a6fc-a2ba4cf358fa.ser
  USER/384e724d-7c54-44e9-a0f5-9d9465618cd3.ser
  USER/745d4c2f-36a1-4e3a-b550-b45cd3ec59c2.ser
  USER/b90b5bf9-9f4a-4f52-b7dd-5ce2d0dc85ea.ser
  USER/bec70406-2ae2-49fe-a5da-303bce6bb9a2.ser
  USER/cb050a5f-3410-45e4-9563-b910a29e323f.ser
  USER/d0671c25-a3a2-431d-a426-6eec52e3e95d.ser
  USER/dd012035-bbe2-43b8-b78c-102896867991.ser
  src/main/java/com/sprint/mission/discodeit/JavaApplication.java
  src/main/java/com/sprint/mission/discodeit/entity/Channel.java
  src/main/java/com/sprint/mission/discodeit/entity/ChannelStatus.java
  src/main/java/com/sprint/mission/discodeit/entity/Message.java
  src/main/java/com/sprint/mission/discodeit/entity/User.java
  src/main/java/com/sprint/mission/discodeit/main/Main.java
  src/main/java/com/sprint/mission/discodeit/repository/ChannelRepository.java
  src/main/java/com/sprint/mission/discodeit/repository/MessageRepository.java
  src/main/java/com/sprint/mission/discodeit/repository/UserRepository.java
  src/main/java/com/sprint/mission/discodeit/repository/file/FileChannelRepository.java
  src/main/java/com/sprint/mission/discodeit/repository/file/FileMessageRepository.java
  src/main/java/com/sprint/mission/discodeit/repository/file/FileUserRepository.java
  src/main/java/com/sprint/mission/discodeit/repository/jcf/JCFUserRepository.java
  src/main/java/com/sprint/mission/discodeit/service/ChannelService.java
  src/main/java/com/sprint/mission/discodeit/service/MessageService.java
  src/main/java/com/sprint/mission/discodeit/service/UserService.java
  src/main/java/com/sprint/mission/discodeit/service/file/FileChannelService.java
  src/main/java/com/sprint/mission/discodeit/service/file/FileMessageService.java
  src/main/java/com/sprint/mission/discodeit/service/file/FileUserService.java
  src/main/java/com/sprint/mission/discodeit/service/jcf/JCFChannelService.java
  src/main/java/com/sprint/mission/discodeit/service/jcf/JCFMessageService.java
  src/main/java/com/sprint/mission/discodeit/service/jcf/JCFUserService.java
Labels: 매운맛🔥

#78 정영진 sprint2
  .gitignore
  .idea/gradle.xml
  build.gradle
  src/main/java/BasicTest.java
  src/main/java/JavaApplication.java
  src/main/java/com/sprint/mission/discodeit/entity/Channel.java
  src/main/java/com/sprint/mission/discodeit/entity/Message.java
  src/main/java/com/sprint/mission/discodeit/entity/User.java
  src/main/java/com/sprint/mission/discodeit/exception/AlreadyChannelMemberException.java
  src/main/java/com/sprint/mission/discodeit/exception/ChannelNotFoundException.java
  src/main/java/com/sprint/mission/discodeit/exception/DuplicateChannelNameException.java
  src/main/java/com/sprint/mission/discodeit/exception/DuplicateLoginIdException.java
  src/main/java/com/sprint/mission/discodeit/exception/MessageNotFoundException.java
  src/main/java/com/sprint/mission/discodeit/exception/NotChannelMemberException.java
  src/main/java/com/sprint/mission/discodeit/exception/UnauthorizedMessageAccessException.java
  src/main/java/com/sprint/mission/discodeit/exception/UserNotFoundException.java
  src/main/java/com/sprint/mission/discodeit/repository/ChannelRepository.java
  src/main/java/com/sprint/mission/discodeit/repository/FileRepository.java
  src/main/java/com/sprint/mission/discodeit/repository/MessageRepository.java
  src/main/java/com/sprint/mission/discodeit/repository/UserRepository.java
  src/main/java/com/sprint/mission/discodeit/repository/file/FileChannelRepository.java
  src/main/java/com/sprint/mission/discodeit/repository/file/FileMessageRepository.java
  src/main/java/com/sprint/mission/discodeit/repository/file/FileUserRepository.java
  src/main/java/com/sprint/mission/discodeit/repository/jcf/JCFChannelRepository.java
  src/main/java/com/sprint/mission/discodeit/repository/jcf/JCFMessageRepository.java
  src/main/java/com/sprint/mission/discodeit/repository/jcf/JCFUserRepository.java
  src/main/java/com/sprint/mission/discodeit/service/ChannelMessageService.java
  src/main/java/com/sprint/mission/discodeit/service/ChannelService.java
  src/main/java/com/sprint/mission/discodeit/service/MessageService.java
  src/main/java/com/sprint/mission/discodeit/service/UserService.java
  src/main/java/com/sprint/mission/discodeit/service/basic/BasicChannelMessageService.java
  src/main/java/com/sprint/mission/discodeit/service/basic/BasicChannelService.java
  src/main/java/com/sprint/mission/discodeit/service/basic/BasicMessageService.java
  src/main/java/com/sprint/mission/discodeit/service/basic/BasicUserService.java
  src/main/java/com/sprint/mission/discodeit/service/file/FileChannelMessageService.java
  src/main/java/com/sprint/mission/discodeit/service/file/FileChannelService.java
  src/main/java/com/sprint/mission/discodeit/service/file/FileMessageService.java
  src/main/java/com/sprint/mission/discodeit/service/file/FileUserService.java
  src/main/java/com/sprint/mission/discodeit/service/jcf/JCFChannelService.java
  src/main/java/com/sprint/mission/discodeit/service/jcf/JCFMessageService.java
  src/main/java/com/sprint/mission/discodeit/service/jcf/JCFUserService.java
  src/test/java/BasicUnitTest/BasicChannelMessageServiceTest.java
  src/test/java/BasicUnitTest/BasicChannelServiceTest.java
  src/test/java/BasicUnitTest/BasicMessageServiceTest.java
  src/test/java/BasicUnitTest/BasicUserServiceTest.java
  src/test/java/RepositoryTest.java
Labels: 매운맛🔥

#132 김재민 sprint3
  .gitattributes
  .gitignore
  HELP.md
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/sprint/mission/discodeit/DiscodeitApplication.java
  src/main/java/com/sprint/mission/discodeit/JavaApplication.java
  src/main/java/com/sprint/mission/discodeit/entity/BinaryContent.java
  src/main/java/com/sprint/mission/discodeit/entity/Channel.java
  src/main/java/com/sprint/mission/discodeit/entity/ChannelType.java
  src/main/java/com/sprint/mission/discodeit/entity/Message.java
  src/main/java/com/sprint/mission/discodeit/entity/ReadStatus.java
  src/main/java/com/sprint/mission/discodeit/entity/User.java
  src/main/java/com/sprint/mission/discodeit/entity/UserStatus.java
  src/main/java/com/sprint/mission/discodeit/repository/ChannelRepository.java
  src/main/java/com/sprint/mission/discodeit/repository/MessageRepository.java
  src/main/java/com/sprint/mission/discodeit/repository/UserRepository.java
  src/main/java/com/sprint/mission/discodeit/repository/file/FileChannelRepository.java
  src/main/java/com/sprint/mission/discodeit/repository/file/FileMessageRepository.java
  src/main/java/com/sprint/mission/discodeit/repository/file/FileUserRepository.java
  src/main/java/com/sprint/mission/discodeit/repository/jcf/JCFChannelRepository.java
  src/main/java/com/sprint/mission/discodeit/repository/jcf/JCFMessageRepository.java
  src/main/java/com/sprint/mission/discodeit/repository/jcf/JCFUserRepository.java
  src/main/java/com/sprint/mission/discodeit/service/basic/BasicChannelService.java
  src/main/java/com/sprint/mission/discodeit/service/basic/BasicMessageService.java
  src/main/java/com/sprint/mission/discodeit/service/basic/BasicUserService.java
  src/main/resources/application.yaml
  src/test/java/com/sprint/mission/discodeit/ApplicationTests.java
Labels: 미완성🛠️

#184 [김동규] sprint4
  src/main/java/com/sprint/mission/discodeit/DiscodeitApplication.java
  src/main/java/com/sprint/mission/discodeit/controller/AuthController.java
  src/main/java/com/sprint/mission/discodeit/controller/BinaryContentController.java
  src/main/java/com/sprint/mission/discodeit/controller/ChannelController.java
  src/main/java/com/sprint/mission/discodeit/controller/MessageController.java
  src/main/java/com/sprint/mission/discodeit/controller/ReadStatusController.java
  src/main/java/com/sprint/mission/discodeit/controller/UserController.java
  src/main/java/com/sprint/mission/discodeit/exception/GlobalExceptionHandler.java
  src/main/java/com/sprint/mission/discodeit/repository/MessageRepository.java
  src/main/java/com/sprint/mission/discodeit/repository/file/FileMessageRepository.java
  src/main/java/com/sprint/mission/discodeit/repository/jcf/JCFMessageRepository.java
  src/main/java/com/sprint/mission/discodeit/service/MessageService.java
  src/main/java/com/sprint/mission/discodeit/service/basic/BasicMessageService.java
  src/main/resources/static/script.js
  src/main/resources/static/styles.css
  src/main/resources/static/user-list.html
Labels: 미완성🛠️, 지각제출⏰

#191 [임규성] sprint5
  Dockerfile
  build.gradle
  docker-compose.yml
  src/main/java/com/sprint/mission/discodeit/controller/ChannelController.java
  src/main/java/com/sprint/mission/discodeit/controller/MessageController.java
  src/main/java/com/sprint/mission/discodeit/controller/UserController.java
  src/main/java/com/sprint/mission/discodeit/domain/dto/AlarmDTO.java
  src/main/java/com/sprint/mission/discodeit/domain/dto/ChannelId.java
  src/main/java/com/sprint/mission/discodeit/domain/dto/FindBiContentIdInDTO.java
  src/main/java/com/sprint/mission/discodeit/domain/dto/UserId.java
  src/main/java/com/sprint/mission/discodeit/domain/entity/ChannelUser.java
  src/main/java/com/sprint/mission/discodeit/domain/enums/ContentType.java
  src/main/java/com/sprint/mission/discodeit/repository/UserRepository.java
  src/main/java/com/sprint/mission/discodeit/repository/file/FileUserRepository.java
  src/main/java/com/sprint/mission/discodeit/service/alarm/AlarmService.java
  src/main/java/com/sprint/mission/discodeit/service/alarm/MessageAlarmService.java
  src/main/java/com/sprint/mission/discodeit/service/basic/BasicMessageService.java
  src/main/java/com/sprint/mission/discodeit/service/basic/BasicReadStatusService.java
  src/main/java/com/sprint/mission/discodeit/service/basic/BasicUserService.java
Labels: 매운맛🔥

#214 [김수연] sprint5
  build.gradle
  src/main/java/com/codeit/mission/discodeit/controller/AuthController.java
  src/main/java/com/codeit/mission/discodeit/controller/BinaryContentController.java
  src/main/java/com/codeit/mission/discodeit/controller/ChannelController.java
  src/main/java/com/codeit/mission/discodeit/controller/MessageController.java
  src/main/java/com/codeit/mission/discodeit/controller/ReadStatusController.java
  src/main/java/com/codeit/mission/discodeit/controller/UserController.java
  src/main/java/com/codeit/mission/discodeit/dto/request/LoginRequest.java
  src/main/java/com/codeit/mission/discodeit/dto/request/UserCreateRequest.java
  src/main/java/com/codeit/mission/discodeit/exception/GlobarExceptionHandler.java
  src/main/resources/application.yml
Labels: 매운맛🔥
